import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideHttpClient, withFetch } from '@angular/common/http';
import { provideRouter } from '@angular/router';
import { provideNzIcons } from 'ng-zorro-antd/icon';
import {
  MenuOutline,
  UserOutline,
  LockOutline,
  MailOutline,
  EyeOutline,
  EyeInvisibleOutline,
  GoogleOutline,
  AppleOutline,
  PhoneOutline,
  EnvironmentOutline,
  SketchOutline,
  DownOutline,
  ArrowRightOutline,
  ThunderboltOutline,
  BarChartOutline,
  TeamOutline,
  SearchOutline,
  ShoppingCartOutline,
  CloseOutline,
  CheckCircleFill,
  ArrowLeftOutline,
  StarFill,
  FacebookFill,
  FacebookOutline,
  TwitterOutline,
  InstagramFill,
  InstagramOutline,
  GithubFill,
  GithubOutline,
  HeartFill,
  CreditCardFill,
  CreditCardOutline,
  SafetyOutline,
  CheckCircleOutline,
  InfoCircleOutline,
  HeartOutline,
  HomeOutline,
  HomeFill,
  FormOutline,
  InboxOutline,
  BaiduOutline,
  SolutionOutline,
  PlusOutline,
  DeleteOutline,
  TagOutline,
  GiftOutline,
  StarOutline,
} from '@ant-design/icons-angular/icons';
import { routes } from './app.routes';
import { provideClientHydration, withEventReplay } from '@angular/platform-browser';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideNzIcons([
      MenuOutline,
      UserOutline,
      LockOutline,
      MailOutline,
      EyeOutline,
      EyeInvisibleOutline,
      GoogleOutline,
      AppleOutline,
      PhoneOutline,
      EnvironmentOutline,
      SketchOutline,
      DownOutline,
      ArrowRightOutline,
      ThunderboltOutline,
      BarChartOutline,
      TeamOutline,
      SearchOutline,
      ShoppingCartOutline,
      CloseOutline,
      CheckCircleFill,
      ArrowLeftOutline,
      StarFill,
      FacebookFill,
      FacebookOutline,
      TwitterOutline,
      InstagramFill,
      InstagramOutline,
      GithubFill,
      GithubOutline,
      HeartOutline,
      HeartFill,
      CreditCardFill,
      CreditCardOutline,
      SafetyOutline,
      CheckCircleOutline,
      InfoCircleOutline,
      HomeOutline,
      HomeFill,
      FormOutline,
      BaiduOutline,
      InboxOutline,
      SolutionOutline,
      PlusOutline,
      DeleteOutline,
      TagOutline,
      GiftOutline,
      StarOutline,
    ]),
    provideRouter(routes),
    provideHttpClient(withFetch()),
    provideClientHydration(withEventReplay()),
  ],
};
